// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace SlackMUDRPG {
	
	
	public partial class TestButton {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.TextBox tb_TextAreaOutput;
		
		protected System.Web.UI.WebControls.Button btn_clear;
		
		protected System.Web.UI.WebControls.Button btn_guid;
		
		protected System.Web.UI.WebControls.TextBox tb_CharID;
		
		protected System.Web.UI.WebControls.TextBox tb_RoomShortcutText;
		
		protected System.Web.UI.WebControls.TextBox tb_ChatText;
		
		protected System.Web.UI.WebControls.Button btn_Say;
		
		protected System.Web.UI.WebControls.Button btn_Shout;
		
		protected System.Web.UI.WebControls.Button btn_Test;
		
		protected System.Web.UI.WebControls.Button btn_GetLocation;
		
		protected System.Web.UI.WebControls.Button btn_CreateCharacter;
		
		protected System.Web.UI.WebControls.Button btn_MoveToRoom;
		
		protected System.Web.UI.WebControls.Button btn_PickUpStick;
		
		protected System.Web.UI.WebControls.Button btn_DropUpStick;
	}
}
